version: '3.4'

services:
  xl.api:
    image: ${DOCKER_REGISTRY-}xlapi
    build:
      context: .
      dockerfile: XL.API/Dockerfile

  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql
    environment:
      SA_PASSWORD: YourStrongPassword123
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
volumes:
  sql-data: